export const ROLES = {
	APPLICATION_MANAGER: {
		ID: 1n,
		LABEL: "APPLICATION_MANAGER_ROLE",
	},
	ATTESTER: {
		ID: 2n,
		LABEL: "ATTESTER_ROLE",
	},
	PERMISSION_MANAGER: {
		ID: 3n,
		LABEL: "PERMISSION_MANAGER_ROLE",
	},
};
